global:
  scrape_interval: 15s
  evaluation_interval: 15s
scrape_configs:

  - job_name: "prometheus"
    static_configs:
      - targets: [ "0.0.0.0:9090" ]

  - job_name: 'SpringMetric'
    metrics_path: '/'
    scrape_interval: 3s
    static_configs:
      - targets: [ '0.0.0.0:8081' ]
        labels:
          application: 'Event Management Platform Metrics'